version: '3'
#
# NB, no specific volumes set, data storage will default to /var/lib/docker/volumes on ubuntu
# clean up with docker volume prune
#
services:

  i2-g-influxdb:
    build:
      context: .
      dockerfile: test-container-config/influxdb/Dockerfile
    ports:
      - "127.0.0.1:8186:8086" # console
    env_file:
      - 'test-container-config/influxdb/influxdb.env'
    network_mode: "host"
  i2-g-grafana:
    build:
      context: .
      dockerfile: test-container-config/grafana/Dockerfile
    ports:
      - "127.0.0.1:4000:3000" # dashboard/console
    env_file:
      - 'test-container-config/grafana/grafana.env'
    depends_on:
      - i2-g-influxdb
    network_mode: "host"
  rest-demo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - i2-g-influxdb
    network_mode: "host"
