spring:
  application:
    name: rest-jpa-metrics-demo

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

metrics:
  environment: local

management:
  influx:
    metrics:
      export:
        enabled: true
        org: myorg
        bucket: springboot
        uri: http://localhost:8086
        token: Rvwf6EnLQkBKGFSkjCY13Fz9AqkPy8MToM0QwnGtQUwseNG9qtffN68lYIndngOxR72FgQ1cQ5C7DL7WXRTB3g==
        compressed: true
        connect-timeout: 1s
        consistency: one
        num-threads: 2
        read-timeout: 10s
        step: 10s
  # expose all metrics endpoints:
  endpoints:
    web:
      exposure:
        include: "*"
